name: fii_notify
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  fresh_dio: ^0.3.2
  json_annotation: ^4.8.0
  dio: ^4.0.0
  get_it: ^7.2.0
  flutter_html: ^2.2.1
  flutter_inappwebview: ^5.7.2+3
  firebase_messaging: ^14.2.6
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  flutter_local_notifications: ^13.0.0
  formz: ^0.5.0+1
  shared_preferences: ^2.0.18
  connectivity_plus: ^3.0.2
  flex_color_scheme: ^7.0.0-dev.3
  dio_http_cache: ^0.3.0
  cached_network_image: ^3.2.3
  intl: ^0.17.0
dependency_overrides:
  flutter_svg: ^1.0.0
  json_serializable: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/images/

  uses-material-design: true
